"""Add bio field to Lecturer model

Revision ID: af8681f2d5f2
Revises: 
Create Date: 2026-02-11 02:46:20.905918

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'af8681f2d5f2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lecturer', schema=None) as batch_op:
        batch_op.add_column(sa.Column('bio', sa.Text(), nullable=True))

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('total_upvotes')
        batch_op.drop_column('reliable_tag')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reliable_tag', sa.INTEGER(), nullable=False))
        batch_op.add_column(sa.Column('total_upvotes', sa.INTEGER(), nullable=False))

    with op.batch_alter_table('lecturer', schema=None) as batch_op:
        batch_op.drop_column('bio')

    # ### end Alembic commands ###
